### ISSUE TITLE
I don’t understand these error messages, let me show you

### ISSUE THREAD

**Issue by jxjxjhjh** [nbr23/ydl-podcast#11]
[youtube] 83kissKqPfc: Downloading API JSON
[youtube] 83kissKqPfc: Downloading API JSON
[info] Writing video description metadata as JSON to: /app/data/手编2/郭德纲 于谦 《老和部队》相声——“迎面白宫墙上写着‘计划生育，人人有责’。”“好吧，美国也宣传这个。”丨无损音质，伴您入眠系列欢迎订阅，持续更新ing [83kissKqPfc][20200406].info.json
ERROR: Cannot write metadata to JSON file /app/data/手编2/郭德纲 于谦 《老和部队》相声——“ 迎面白宫墙上写着‘计划生育，人人有责’。”“好吧，美国也宣传这个。”丨无损音质，伴您入眠系列欢 迎订阅，持续更新ing [83kissKqPfc][20200406].info.json
ERROR: Cannot write metadata to JSON file /app/data/手编2/郭德纲 于谦 《老和部队》相声——“ 迎面白宫墙上写着‘计划生育，人人有责’。”“好吧，美国也宣传这个。”丨无损音质，伴您入眠系列欢 迎订阅，持续更新ing [83kissKqPfc][20200406].info.json
[youtube] Ui-I3ozdUwM: Downloading webpage
WARNING: Unable to download webpage: HTTP Error 429: Too Many Requests
[youtube] Ui-I3ozdUwM: Downloading API JSON
[youtube] Ui-I3ozdUwM: Downloading API JSON
[info] Writing video description metadata as JSON to: /app/data/手编2/郭德纲 于谦 《我要上春晚》经典相声——“终于有一个戏碰到个女导演。我想，为了艺术我献身去吧。当当当一敲门，我一看 这事成不了。制片人在屋里躺着呢。”丨无损音质，伴您入眠系列丨欢迎订阅，持续更新ing [Ui-I3ozdUwM][20200224].info.json
ERROR: Cannot write metadata to JSON file /app/data/手编2/郭德纲 于谦 《我要上春晚》经典相声——“终于有一个戏碰到个女导演。我想，为了艺术我献身去吧。当当当一敲门，我一看这事成不了。 制片人在屋里躺着呢。”丨无损音质，伴您入眠系列丨欢迎订阅，持续更新ing [Ui-I3ozdUwM][20200224].info.json
ERROR: Cannot write metadata to JSON file /app/data/手编2/郭德纲 于谦 《我要上春晚》经典相声——“终于有一个戏碰到个女导演。我想，为了艺术我献身去吧。当当当一敲门，我一看这事成不了。 制片人在屋里躺着呢。”丨无损音质，伴您入眠系列丨欢迎订阅，持续更新ing [Ui-I3ozdUwM][20200224].info.json
Traceback (most recent call last):
  File "/usr/bin/ydl_podcast", line 33, in <module>
    sys.exit(load_entry_point('ydl-podcast==1.0', 'console_scripts', 'ydl_podcast')())
  File "/usr/lib/python3.8/site-packages/ydl_podcast/__main__.py", line 35, in main
    download(sub)
  File "/usr/lib/python3.8/site-packages/ydl_podcast/__init__.py", line 146, in download
    with open(mdfile_name, 'w+') as f:
OSError: [Errno 36] Filename too long: '/app/data/手编2/.Ui-I3ozdUwM.郭德纲 于谦 《我要上 春晚》经典相声——“终于有一个戏碰到个女导演。我想，为了艺术我献身去吧。当当当一敲门，我一看 这事成不了。制片人在屋里躺着呢。”丨无损音质，伴您入眠系列丨欢迎订阅，持续更新ing.meta'

**Comment by nbr23** [comment]
Hi @jxjxjhjh,

I have added a `filename_template` option in the config file in https://github.com/nbr23/ydl-podcast/commit/04787314eb879266acc208bb5fbeaeff664a9083
You can set it to not include the title, or to include less information so that the filenames are shorter and don't cause issues on your filesystem.

For example:
```yaml
    filename_template: '%(id)s.%(ext)s' # Filename will be just ID.extension
```

Let me know if that helps.

**Comment by jxjxjhjh** [comment]
WARNING: Unable to download webpage: HTTP Error 429: Too Many Requests

Because it is crawled too frequently, it takes a little time to test.

**Comment by nbr23** [comment]
Yeah that can happen if you poll too frequently. Maybe adjust your job to run less often.

**Comment by jxjxjhjh** [comment]
> Yeah that can happen if you poll too frequently. Maybe adjust your job to run less often.

after testing Very good, solved my problem.
