### ISSUE TITLE
youtube_dl and mkv

### ISSUE THREAD

**Issue by z0mn** [nbr23/ydl-podcast#2]
Hi again! Some videos (like from the channel LGR) will always download in the highest quality, which results in a webm+m4a being merged into an MKV, which isn't compatible with Apple Podcasts.

Would it be possible to add a config option to choose Force MP4?

**Comment by z0mn** [comment]
FWIW, I apologize for making a feature request under Issues.

I was able to hobble together a version that works for me:

**ydl_podcast.py**
Added this at line 82:
```
    if sub['force_mp4']:
        options['format'] = 'bestvideo[ext=mp4]+bestaudio[ext=m4a]'
```

then added this to **config.yaml** under one of the feeds:
`    force_mp4: True # Try force mp4`

I wish there was a way to "force" ext=mp4 and resolution up to 720p.

**Comment by nbr23** [comment]
No worries, I am wrapping up on a more generic solution, will push that in a bit.
Regarding forcing 720p, I am not sure that is doable unfortunately, but I will keep looking.

**Comment by z0mn** [comment]
Sounds good! I just added about 20 new subs to my config, and am monitoring it now. Hoping I don't run into throttling by YT (only downloading last 1-5 videos of each channel).

**Comment by z0mn** [comment]
HTTP Error 429 while scanning a playlist with 400+ pages:
```
[youtube:playlist] UUXIJgqnII2ZOINSWNOGFThA: Downloading page #442
ERROR: Unable to download JSON metadata: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

This is a bummer for big channels and might defeat the purpose of this script. I know this is on youtube-dl, but if we could add a delay (or skip the re-scanning altogether), this could be fixed... What do you think?

**Comment by nbr23** [comment]
Alright, for the initial issue, check https://github.com/nbr23/ydl-podcast/commit/0e7f281ffb6595ea88717420896ac633f1e85279
If you add `format: mp4` to your sub it should do the trick.

I am checking on the second issue. Rate limiting might help us out.

**Comment by nbr23** [comment]
For your second issue, I think rate limiting is worth a shot.
https://github.com/nbr23/ydl-podcast/commit/a902ee4294be73698b881d630b8d1b9bab990c91 adds the possibility add raw youtube-dl options, so in your case you could try rate limitting by adding the following in your config.yaml:
```
ydl_options:
  ratelimit: 512000
```
Note that the value is in B/s, so 512000 will be 512kB/s.

Unfortunately youtube-dl doesn't support pausing between downloads within a playlist. We could add a pause between each playlist in the script here, but I am not sure it would help much.
Let me know if rate limiting helps though.

Thanks!

**Comment by z0mn** [comment]
Excellent. Will give it a shot once my throttle expires. I think the pausing between checking a single page in a playlist would address it. I wonder if I could get into the youtube-dl script itself and manually enter that...

**Comment by nbr23** [comment]
that's not necessarily the most obvious one, but it would go like this:
```
ydl_options:
  ratelimit: 512000
  source_address: "0.0.0.0"
```

(note that ydl_options can be specified per sub, or at top level to be applied to all subs ;))
