### ISSUE TITLE
Request to support bilibili.com website

### ISSUE THREAD

**Issue by jxjxjhjh** [nbr23/ydl-podcast#7]
I want to download videos from the bilibili website in China, hoping to support this website, youtube-dl itself supports this website.

**Comment by nbr23** [comment]
Hi @jxjxjhjh, if youtube-dl supports then this should support it too, since it's based on youtube-dl.
Are you having any specific issues?

**Comment by jxjxjhjh** [comment]
I think that although youtube-dl can download videos from bilibili.com, ydlpod may not have set how to scan bilibili's webpage to get a list of video playback pages, which caused me to fail the test.
Of course, I do not fully understand the principle of ydlpod, if I can hope to have a bilibili.com configuration file demonstration.
