### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by jxjxjhjh** [nbr23/ydl-podcast#8]
WARNING: Writing cache to '/.cache/youtube-dl/youtube-sigfuncs/js_838cc154_114.json' failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/youtube_dl/cache.py", line 49, in store
    os.makedirs(os.path.dirname(fn))
  File "/usr/local/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/.cache'

**Comment by nbr23** [comment]
Hi @jxjxjhjh,
In your config.yml, try setting:
```
ydl_options: # youtube-dl options
  cachedir:  "SOME_DIR_YOU_HAVE_RIGHTS_TO"
```

Or even:
```
ydl_options: # youtube-dl options
  cachedir:  False
```

Let me know!
Cheers,

**Comment by jxjxjhjh** [comment]
Obstacles encountered during the test:
```
Traceback (most recent call last):
  File "/usr/local/bin/ydl_podcast", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/ydl_podcast/__main__.py", line 35, in main
    download(sub)
  File "/usr/local/lib/python3.9/site-packages/ydl_podcast/__init__.py", line 146, in download
    with open(mdfile_name, 'w+') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/app/data/手动编辑条目/.p9WSnqZ-nWE.*FIRST TIME* CRACKING EVERY PART of the Body! | ASMR OSTEOPATH / CHIROPRACTIC ADJUSTMENT.meta'
```

I'm not sure if the symbols in the title cause this problem. I hope to add a feature that removes all symbols in the file name.
My Podcast client does not support special symbols in files well, and often encounters problems that cannot be played.

**Comment by nbr23** [comment]
The directory `/app/data/` exists on your system ?

**Comment by jxjxjhjh** [comment]
> The directory `/app/data/` exists on your system ?

yes
https://github.com/jxjxjhjh/docker-ydlpod

**Comment by nbr23** [comment]
Thanks,
I see you have the volume mapped as such:
```
      - /var/www:/app
```
But just to be sure, on your host system, the directory `/var/www/data` (which would correspond to `/app/data` in your container) exists ?

**Comment by jxjxjhjh** [comment]
> Thanks,
> I see you have the volume mapped as such:
> 
> ```
>       - /var/www:/app
> ```
> 
> But just to be sure, on your host system, the directory `/var/www/data` (which would correspond to `/app/data` in your container) exists ?



Yes, it exists.
I just thought that it might be a permission problem, because I specified the user as a normal user in the latest version of the dockerfile. This problem occurred after that. I will modify this setting in the near future to verify my guess.

In addition, it is hoped that the problem of stopping crawling due to the implementation of special symbols in the video title can be solved as soon as possible, which is a high priority issue that affects the use.

**Comment by nbr23** [comment]
Hi @jxjxjhjh perhaps the user you are using to run the container doesn't have write access to `/var/www` on your docker host ?

**Comment by jxjxjhjh** [comment]
Because the Google translation is not accurate enough, I can't understand what you mean, but this problem seems to be rarely seen after the random file name function has been added. I am not sure, but it is just the impression.
Because of the upcoming special day, it is temporarily inconvenient for me to continue to study these issues. I plan to stop using vpn to access US websites before June 15th.
Thank you for your help, we will contact you later.

**Comment by nbr23** [comment]
Ok, thanks

**Comment by jxjxjhjh** [comment]
ydl_options:
      cachedir:  False
Effective and can solve the problem.
The reason for the problem is that user 1000:1000 is added to my dockerfile. This is to manually manage files through a special method, because the automatic cleaning function of ydlpod does not seem to exist, and the old files cannot be automatically cleaned up.
